#!/usr/bin/env bash
# Build a small scratch jj repo with a realistic in-flight change so the
# gander demo (docs/demo.tape) has something interesting to review.
set -euo pipefail

dir="${1:?usage: demo-fixture.sh DIR}"

rm -rf "$dir"
mkdir -p "$dir"
cd "$dir"

jj git init >/dev/null

mkdir -p src

cat > src/lib.rs <<'EOF'
pub mod parser;

pub fn greet(name: &str) -> String {
    format!("hello, {name}")
}
EOF

cat > src/parser.rs <<'EOF'
/// Parse a comma separated list of tags.
pub fn parse_tags(input: &str) -> Vec<String> {
    input.split(',').map(|tag| tag.to_string()).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_tags() {
        assert_eq!(parse_tags("a,b"), vec!["a", "b"]);
    }
}
EOF

cat > README.md <<'EOF'
# tagger

A tiny demo crate for taking a gander at jj changes.
EOF

cat > Cargo.lock <<'EOF'
# This file is automatically generated by Cargo.
version = 4

[[package]]
name = "tagger"
version = "0.1.0"
EOF

jj describe -m 'feat: initial tagger crate' >/dev/null
jj bookmark create main -r @ >/dev/null
jj new >/dev/null

# The change under review: trim + skip empties in the parser, a new lexer
# module, a README note, and lockfile churn.
cat > src/parser.rs <<'EOF'
/// Parse a comma separated list of tags.
///
/// Tags are trimmed and empty entries are skipped.
pub fn parse_tags(input: &str) -> Vec<String> {
    input
        .split(',')
        .map(str::trim)
        .filter(|tag| !tag.is_empty())
        .map(|tag| tag.to_lowercase())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_tags() {
        assert_eq!(parse_tags("a,b"), vec!["a", "b"]);
    }

    #[test]
    fn trims_and_skips_empty_tags() {
        assert_eq!(parse_tags(" a , ,B"), vec!["a", "b"]);
    }
}
EOF

cat > src/lexer.rs <<'EOF'
/// Token kinds produced by the lexer.
#[derive(Debug, PartialEq)]
pub enum Token {
    Word(String),
    Comma,
}

pub fn lex(input: &str) -> Vec<Token> {
    let mut tokens = Vec::new();
    for part in input.split_inclusive(',') {
        let word = part.trim_end_matches(',').trim();
        if !word.is_empty() {
            tokens.push(Token::Word(word.to_string()));
        }
        if part.ends_with(',') {
            tokens.push(Token::Comma);
        }
    }
    tokens
}
EOF

cat > src/lib.rs <<'EOF'
pub mod lexer;
pub mod parser;

pub fn greet(name: &str) -> String {
    format!("hello, {name}")
}
EOF

cat >> README.md <<'EOF'

Tags are normalized to lowercase since v0.2.
EOF

cat > Cargo.lock <<'EOF'
# This file is automatically generated by Cargo.
version = 4

[[package]]
name = "tagger"
version = "0.2.0"

[[package]]
name = "unicode-xid"
version = "0.2.4"
EOF

jj describe -m 'feat: normalize tags and add lexer' >/dev/null

printf 'demo fixture ready at %s\n' "$dir"
