use super::*;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct SpotlightIdentity {
    pub(super) step_id: String,
    pub(super) part: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct WebPresentationState {
    pub(super) identity: SpotlightIdentity,
    pub(super) index: usize,
    pub(super) stale: bool,
}

#[derive(Debug, Clone)]
pub(super) struct PresentEvent {
    pub(super) sequence: u64,
    pub(super) command: &'static str,
    pub(super) status: Value,
    pub(super) target: Option<PresentTarget>,
    pub(super) note: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
pub(super) struct PresentTarget {
    pub(super) path: String,
    pub(super) line: Option<usize>,
    pub(super) end_line: Option<usize>,
    pub(super) region_id: Option<String>,
    pub(super) row_id: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub(super) struct WebInteractions {
    pub(super) next_sequence: u64,
    pub(super) next_connection: u64,
    pub(super) tabs: std::collections::BTreeMap<String, TabInteraction>,
}

#[derive(Debug, Clone)]
pub(super) struct TabInteraction {
    /// Server-observed activity order, used only for controlling-tab
    /// arbitration.
    pub(super) sequence: u64,
    /// Last accepted sequence generated by this browser tab. This is distinct
    /// from `sequence`: client ordering rejects delayed keepalive requests,
    /// while server ordering deterministically compares different tabs.
    pub(super) client_sequence: u64,
    pub(super) connection: u64,
    pub(super) connected: bool,
    pub(super) focus: Option<BrowserFocus>,
    pub(super) busy: Option<String>,
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
pub(super) struct BrowserFocus {
    pub(super) path: Option<String>,
    pub(super) old_line: Option<usize>,
    pub(super) new_line: Option<usize>,
    pub(super) hunk_header: Option<String>,
    pub(super) pane: String,
}

#[derive(Debug, Deserialize)]
pub(super) struct InteractionReport {
    pub(super) tab_id: String,
    pub(super) client_sequence: u64,
    #[serde(default)]
    pub(super) focus: Option<BrowserFocus>,
    #[serde(default)]
    pub(super) busy: Option<String>,
}

impl WebInteractions {
    pub(super) fn connect(&mut self, tab_id: &str) -> Option<u64> {
        if !valid_tab_id(tab_id) {
            return None;
        }
        self.next_connection = self.next_connection.saturating_add(1);
        let connection = self.next_connection;
        self.tabs
            .entry(tab_id.to_owned())
            .and_modify(|tab| {
                tab.connection = connection;
                tab.connected = true;
            })
            .or_insert(TabInteraction {
                sequence: 0,
                client_sequence: 0,
                connection,
                connected: true,
                focus: None,
                busy: None,
            });
        Some(connection)
    }

    pub(super) fn disconnect(&mut self, tab_id: &str, connection: u64) {
        if self
            .tabs
            .get(tab_id)
            .is_some_and(|tab| tab.connection == connection)
        {
            self.tabs.remove(tab_id);
        }
    }

    /// Apply a report only to a tab with an active SSE lease. POSTs never
    /// establish liveness: a report racing before SSE setup or arriving after
    /// disconnect is harmless. Reordered reports are also harmless.
    pub(super) fn report(&mut self, report: InteractionReport) -> Result<bool, &'static str> {
        if !valid_tab_id(&report.tab_id) {
            return Err("invalid tab_id");
        }
        if report
            .busy
            .as_deref()
            .is_some_and(|mode| !matches!(mode, "search" | "dialog" | "comment editor"))
        {
            return Err("invalid busy mode");
        }
        if report
            .focus
            .as_ref()
            .is_some_and(|focus| !matches!(focus.pane.as_str(), "files" | "diff"))
        {
            return Err("invalid focus pane");
        }
        let Some(tab) = self.tabs.get_mut(&report.tab_id) else {
            return Ok(false);
        };
        if !tab.connected || report.client_sequence <= tab.client_sequence {
            return Ok(false);
        }
        self.next_sequence = self.next_sequence.saturating_add(1);
        tab.sequence = self.next_sequence;
        tab.client_sequence = report.client_sequence;
        tab.focus = report.focus;
        tab.busy = report.busy;
        Ok(true)
    }

    /// Deterministic controlling-tab arbitration: greatest server-observed
    /// input sequence wins, with tab id as an explicit tie-breaker.
    pub(super) fn controlling(&self) -> Option<(&str, &TabInteraction)> {
        self.tabs
            .iter()
            .filter(|(_, tab)| tab.connected)
            .max_by_key(|(id, tab)| (tab.sequence, id.as_str()))
            .map(|(id, tab)| (id.as_str(), tab))
    }
}

pub(super) fn valid_tab_id(tab_id: &str) -> bool {
    !tab_id.is_empty()
        && tab_id.len() <= 128
        && tab_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
}
