use globset::{Glob, GlobSet, GlobSetBuilder};
use serde::Deserialize;

use crate::diff::{DiffLineKind, FileDiff};

/// How many leading lines of the new file content are scanned for
/// generated-code markers.
const HEADER_SCAN_LINES: usize = 10;

/// Case-insensitive markers that generators conventionally place near the top
/// of emitted files.
const GENERATED_CONTENT_MARKERS: &[&str] = &[
    "@generated",
    "do not edit",
    "code generated by",
    "automatically generated",
    "autogenerated",
    "auto-generated",
    "generated by",
];

#[derive(Debug, Clone, Copy, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum GeneratedPreset {
    Lockfiles,
    ApiClients,
    VendoredAssets,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct GeneratedPolicy {
    pub presets: Vec<GeneratedPreset>,
    pub globs: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct GeneratedMatcher {
    set: GlobSet,
}

impl GeneratedMatcher {
    pub fn new(policy: &GeneratedPolicy) -> Result<Self, globset::Error> {
        let mut builder = GlobSetBuilder::new();
        for pattern in policy.patterns() {
            builder.add(Glob::new(&pattern)?);
        }
        Ok(Self {
            set: builder.build()?,
        })
    }

    pub fn is_match(&self, path: &str) -> bool {
        self.set.is_match(path)
    }
}

impl GeneratedPolicy {
    fn patterns(&self) -> Vec<String> {
        let mut patterns = Vec::new();
        for preset in &self.presets {
            patterns.extend(
                preset
                    .patterns()
                    .iter()
                    .map(|pattern| (*pattern).to_owned()),
            );
        }
        patterns.extend(self.globs.clone());
        patterns
    }
}

impl GeneratedPreset {
    fn patterns(&self) -> &'static [&'static str] {
        match self {
            Self::Lockfiles => &[
                "Cargo.lock",
                "package-lock.json",
                "pnpm-lock.yaml",
                "yarn.lock",
                "Gemfile.lock",
                "go.sum",
                "poetry.lock",
            ],
            Self::ApiClients => &[
                "**/generated/**",
                "**/gen/**",
                "**/*generated*",
                "**/openapi/**",
                "**/graphql/generated/**",
                "**/__generated__/**",
            ],
            Self::VendoredAssets => &[
                "**/*.min.js",
                "**/*.min.css",
                "vendor/**",
                "third_party/**",
                "dist/**",
            ],
        }
    }
}

/// Content heuristic: true when the visible top of the file (new side)
/// carries a conventional generated-code marker like `@generated` or
/// `DO NOT EDIT`. Only the first [`HEADER_SCAN_LINES`] file lines are
/// considered, so markers merely mentioned deep in a diff do not match.
pub fn diff_content_looks_generated(diff: &FileDiff) -> bool {
    diff.hunks
        .iter()
        .flat_map(|hunk| hunk.lines.iter())
        .filter(|line| line.kind != DiffLineKind::Removed)
        .filter_map(|line| Some((line.new_lineno?, line.text.as_str())))
        .take_while(|(new_lineno, _)| *new_lineno <= HEADER_SCAN_LINES)
        .any(|(_, text)| {
            let text = text.to_ascii_lowercase();
            GENERATED_CONTENT_MARKERS
                .iter()
                .any(|marker| text.contains(marker))
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::diff::DiffSet;

    #[test]
    fn lockfile_preset_matches_common_lockfiles() {
        let matcher = GeneratedMatcher::new(&GeneratedPolicy {
            presets: vec![GeneratedPreset::Lockfiles],
            globs: Vec::new(),
        })
        .unwrap();

        assert!(matcher.is_match("Cargo.lock"));
        assert!(matcher.is_match("pnpm-lock.yaml"));
        assert!(!matcher.is_match("Cargo.toml"));
    }

    #[test]
    fn api_client_preset_matches_nested_generated_paths() {
        let matcher = GeneratedMatcher::new(&GeneratedPolicy {
            presets: vec![GeneratedPreset::ApiClients],
            globs: Vec::new(),
        })
        .unwrap();

        assert!(matcher.is_match("src/graphql/generated/types.ts"));
        assert!(matcher.is_match("client/__generated__/schema.ts"));
        assert!(!matcher.is_match("src/app.rs"));
    }

    #[test]
    fn custom_globs_are_combined_with_presets() {
        let matcher = GeneratedMatcher::new(&GeneratedPolicy {
            presets: vec![GeneratedPreset::Lockfiles],
            globs: vec!["schemas/*.json".to_owned()],
        })
        .unwrap();

        assert!(matcher.is_match("Cargo.lock"));
        assert!(matcher.is_match("schemas/openapi.json"));
    }

    #[test]
    fn invalid_custom_glob_errors() {
        let result = GeneratedMatcher::new(&GeneratedPolicy {
            presets: Vec::new(),
            globs: vec!["[".to_owned()],
        });

        assert!(result.is_err());
    }

    fn first_file(diff_text: &str) -> FileDiff {
        DiffSet::parse(diff_text).unwrap().files.remove(0)
    }

    #[test]
    fn header_marker_marks_file_as_generated() {
        let file = first_file(
            r#"diff --git a/client/api.ts b/client/api.ts
--- /dev/null
+++ b/client/api.ts
@@ -0,0 +1,4 @@
+// Code generated by openapi-codegen. DO NOT EDIT.
+export interface Widget {
+    id: string;
+}
"#,
        );

        assert!(diff_content_looks_generated(&file));
    }

    #[test]
    fn at_generated_marker_matches_case_insensitively() {
        let file = first_file(
            r#"diff --git a/schema.py b/schema.py
--- /dev/null
+++ b/schema.py
@@ -0,0 +1,2 @@
+# @Generated from schema.proto
+WIDGETS = []
"#,
        );

        assert!(diff_content_looks_generated(&file));
    }

    #[test]
    fn markers_past_the_file_header_do_not_match() {
        let file = first_file(
            r#"diff --git a/docs/notes.md b/docs/notes.md
--- a/docs/notes.md
+++ b/docs/notes.md
@@ -40,3 +40,4 @@
 context
+Some tools write DO NOT EDIT banners.
 more context
"#,
        );

        assert!(!diff_content_looks_generated(&file));
    }

    #[test]
    fn plain_new_files_are_not_generated() {
        let file = first_file(
            r#"diff --git a/src/app.rs b/src/app.rs
--- /dev/null
+++ b/src/app.rs
@@ -0,0 +1,2 @@
+fn main() {
+}
"#,
        );

        assert!(!diff_content_looks_generated(&file));
    }
}
